import Head from 'next/head'
import { useState } from 'react';
import { MouseEventHandler } from 'react';
import {LazyImage} from '../components/LazyImage'

//generate a random fuction between 1 and 123
const random = () => Math.floor(Math.random() * 123) + 1;
//generate a random id
const generateId = () => Math.random().toString(36).substring(2,9)

type ImageItem = { id:string , url:string}

export default function Home() {

  const [images, setImages] = useState<Array<ImageItem>>([])

  const addNewFox: MouseEventHandler<HTMLButtonElement> = (event) =>{
    event.preventDefault();
    const newImageItem: ImageItem = {id: generateId(), url:`https://randomfox.ca/images/${random()}.jpg`}
    setImages([...images, newImageItem])
  }

  return (
    <>
      <Head>
        <title>Random Foxes Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@400;500;700&display=swap" rel="stylesheet"></link>
      </Head>

      <main className='flex flex-col justify-center items-center'>
        <div className='w-full h-[80px] bg-orange-500 flex justify-center items-center shadow-xl'>
          <h1 className='text-2xl font-bold text-stone-50'>RANDOM FOXES IMAGES GENERATOR</h1>
        </div>
          <h1 className="text-3xl font-bold underline"></h1>
          <button onClick={addNewFox} className='my-6 bg-transparent shadow-xl hover:bg-orange-500 text-orange-500 font-semibold text-lg hover:text-white py-1 px-3 border border-orange-500 hover:border-transparent rounded'>Get a  🦊</button>
          <ul className='w-11/12 mx-auto flex flex-wrap justify-center'>
            {images.map(({id,url}) =>(
            <li key={id} className='w-full m-4 rounded-md bg-orange-300 shadow-xl md:w-1/3'>
              <LazyImage src={url} onClick={()=>console.log('hey')} className='w-full h-[350px] shadow-xl object-cover rounded-md'/>
            </li>
          ))}
           </ul>
      </main>
    </>
  )
}
